# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventas.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(971, 627)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu_lateral = QtWidgets.QFrame(self.centralwidget)
        self.menu_lateral.setMaximumSize(QtCore.QSize(300, 16777215))
        self.menu_lateral.setStyleSheet("#menu_lateral {\n"
"    background-color: rgb(65, 107, 191);\n"
"}")
        self.menu_lateral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_lateral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_lateral.setObjectName("menu_lateral")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menu_lateral)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo_cafe_indigo = QtWidgets.QLabel(self.menu_lateral)
        self.logo_cafe_indigo.setMinimumSize(QtCore.QSize(89, 89))
        self.logo_cafe_indigo.setMaximumSize(QtCore.QSize(89, 89))
        self.logo_cafe_indigo.setText("")
        self.logo_cafe_indigo.setPixmap(QtGui.QPixmap("resources/img/icono_cafe.png"))
        self.logo_cafe_indigo.setScaledContents(True)
        self.logo_cafe_indigo.setWordWrap(False)
        self.logo_cafe_indigo.setObjectName("logo_cafe_indigo")
        self.verticalLayout_2.addWidget(self.logo_cafe_indigo, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, 4, -1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.boton_ventas_totales = QtWidgets.QPushButton(self.menu_lateral)
        self.boton_ventas_totales.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.boton_ventas_totales.setAutoFillBackground(False)
        self.boton_ventas_totales.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"    padding: 10px;\n"
"}")
        self.boton_ventas_totales.setObjectName("boton_ventas_totales")
        self.horizontalLayout_3.addWidget(self.boton_ventas_totales, 0, QtCore.Qt.AlignRight)
        self.boton_ventas_totales_desplegable = QtWidgets.QToolButton(self.menu_lateral)
        self.boton_ventas_totales_desplegable.setStyleSheet("border: none;")
        self.boton_ventas_totales_desplegable.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/img/icono_desplegable.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_ventas_totales_desplegable.setIcon(icon)
        self.boton_ventas_totales_desplegable.setObjectName("boton_ventas_totales_desplegable")
        self.horizontalLayout_3.addWidget(self.boton_ventas_totales_desplegable)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.opciones_ventas_totales = QtWidgets.QWidget(self.menu_lateral)
        self.opciones_ventas_totales.setStyleSheet("")
        self.opciones_ventas_totales.setObjectName("opciones_ventas_totales")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.opciones_ventas_totales)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(80, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.boton_ventas_totales_diarias = QtWidgets.QPushButton(self.opciones_ventas_totales)
        self.boton_ventas_totales_diarias.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.boton_ventas_totales_diarias.setAutoFillBackground(False)
        self.boton_ventas_totales_diarias.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}")
        self.boton_ventas_totales_diarias.setObjectName("boton_ventas_totales_diarias")
        self.verticalLayout_4.addWidget(self.boton_ventas_totales_diarias, 0, QtCore.Qt.AlignRight)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.boton_ventas_totales_mensuales = QtWidgets.QPushButton(self.opciones_ventas_totales)
        self.boton_ventas_totales_mensuales.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.boton_ventas_totales_mensuales.setAutoFillBackground(False)
        self.boton_ventas_totales_mensuales.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"")
        self.boton_ventas_totales_mensuales.setObjectName("boton_ventas_totales_mensuales")
        self.verticalLayout_4.addWidget(self.boton_ventas_totales_mensuales, 0, QtCore.Qt.AlignRight)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.boton_ventas_totales_anuales = QtWidgets.QPushButton(self.opciones_ventas_totales)
        self.boton_ventas_totales_anuales.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.boton_ventas_totales_anuales.setAutoFillBackground(False)
        self.boton_ventas_totales_anuales.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"")
        self.boton_ventas_totales_anuales.setObjectName("boton_ventas_totales_anuales")
        self.verticalLayout_4.addWidget(self.boton_ventas_totales_anuales, 0, QtCore.Qt.AlignRight)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addWidget(self.opciones_ventas_totales)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, 4, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.boton_ventas_individuales = QtWidgets.QPushButton(self.menu_lateral)
        self.boton_ventas_individuales.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.boton_ventas_individuales.setAutoFillBackground(False)
        self.boton_ventas_individuales.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"    padding: 10px;\n"
"}")
        self.boton_ventas_individuales.setObjectName("boton_ventas_individuales")
        self.horizontalLayout_4.addWidget(self.boton_ventas_individuales, 0, QtCore.Qt.AlignRight)
        self.boton_ventas_individuales_desplegable = QtWidgets.QToolButton(self.menu_lateral)
        self.boton_ventas_individuales_desplegable.setStyleSheet("border: none;")
        self.boton_ventas_individuales_desplegable.setText("")
        self.boton_ventas_individuales_desplegable.setIcon(icon)
        self.boton_ventas_individuales_desplegable.setObjectName("boton_ventas_individuales_desplegable")
        self.horizontalLayout_4.addWidget(self.boton_ventas_individuales_desplegable)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.opciones_ventas_individuales = QtWidgets.QWidget(self.menu_lateral)
        self.opciones_ventas_individuales.setStyleSheet("")
        self.opciones_ventas_individuales.setObjectName("opciones_ventas_individuales")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.opciones_ventas_individuales)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(80, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.boton_ventas_individuales_diarias = QtWidgets.QPushButton(self.opciones_ventas_individuales)
        self.boton_ventas_individuales_diarias.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.boton_ventas_individuales_diarias.setAutoFillBackground(False)
        self.boton_ventas_individuales_diarias.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}")
        self.boton_ventas_individuales_diarias.setObjectName("boton_ventas_individuales_diarias")
        self.verticalLayout_5.addWidget(self.boton_ventas_individuales_diarias, 0, QtCore.Qt.AlignRight)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.boton_ventas_individuales_mensuales = QtWidgets.QPushButton(self.opciones_ventas_individuales)
        self.boton_ventas_individuales_mensuales.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.boton_ventas_individuales_mensuales.setAutoFillBackground(False)
        self.boton_ventas_individuales_mensuales.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}")
        self.boton_ventas_individuales_mensuales.setObjectName("boton_ventas_individuales_mensuales")
        self.verticalLayout_5.addWidget(self.boton_ventas_individuales_mensuales, 0, QtCore.Qt.AlignRight)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.boton_ventas_individuales_anuales = QtWidgets.QPushButton(self.opciones_ventas_individuales)
        self.boton_ventas_individuales_anuales.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.boton_ventas_individuales_anuales.setAutoFillBackground(False)
        self.boton_ventas_individuales_anuales.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}")
        self.boton_ventas_individuales_anuales.setObjectName("boton_ventas_individuales_anuales")
        self.verticalLayout_5.addWidget(self.boton_ventas_individuales_anuales, 0, QtCore.Qt.AlignRight)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addWidget(self.opciones_ventas_individuales)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, -1, 4, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.boton_empleados = QtWidgets.QPushButton(self.menu_lateral)
        self.boton_empleados.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.boton_empleados.setAutoFillBackground(False)
        self.boton_empleados.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"    padding: 10px;\n"
"}")
        self.boton_empleados.setObjectName("boton_empleados")
        self.horizontalLayout_5.addWidget(self.boton_empleados)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem14)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, 4, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.boton_cerrar = QtWidgets.QPushButton(self.menu_lateral)
        self.boton_cerrar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.boton_cerrar.setAutoFillBackground(False)
        self.boton_cerrar.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"    padding: 10px;\n"
"}")
        self.boton_cerrar.setObjectName("boton_cerrar")
        self.horizontalLayout_6.addWidget(self.boton_cerrar)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addWidget(self.menu_lateral)
        self.frame_informacion = QtWidgets.QFrame(self.centralwidget)
        self.frame_informacion.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_informacion.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_informacion.setStyleSheet("background-color: rgb(167, 199, 243);")
        self.frame_informacion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_informacion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_informacion.setObjectName("frame_informacion")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_informacion)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stacked_widget_paginas = QtWidgets.QStackedWidget(self.frame_informacion)
        self.stacked_widget_paginas.setObjectName("stacked_widget_paginas")
        self.pagina_por_defecto = QtWidgets.QWidget()
        self.pagina_por_defecto.setObjectName("pagina_por_defecto")
        self.label = QtWidgets.QLabel(self.pagina_por_defecto)
        self.label.setGeometry(QtCore.QRect(140, 230, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.pagina_por_defecto)
        self.label_2.setGeometry(QtCore.QRect(180, 330, 47, 13))
        self.label_2.setObjectName("label_2")
        self.stacked_widget_paginas.addWidget(self.pagina_por_defecto)
        self.pagina_ventas_totales_diarias = QtWidgets.QWidget()
        self.pagina_ventas_totales_diarias.setObjectName("pagina_ventas_totales_diarias")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.pagina_ventas_totales_diarias)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.pagina_ventas_totales_diarias)
        self.frame_2.setStyleSheet("")
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setMinimumSize(QtCore.QSize(0, 70))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget.setObjectName("widget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_11.setContentsMargins(-1, -1, 9, 9)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_tipo_usuario_ventas_totales_diarias = QtWidgets.QLabel(self.widget)
        self.label_tipo_usuario_ventas_totales_diarias.setMinimumSize(QtCore.QSize(0, 40))
        self.label_tipo_usuario_ventas_totales_diarias.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_tipo_usuario_ventas_totales_diarias.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: bold;\n"
"    font-size: 22px;\n"
"}")
        self.label_tipo_usuario_ventas_totales_diarias.setObjectName("label_tipo_usuario_ventas_totales_diarias")
        self.verticalLayout_11.addWidget(self.label_tipo_usuario_ventas_totales_diarias, 0, QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 3))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 4))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 2px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_11.addWidget(self.frame_3, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.widget)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("QFrame {\n"
"    background-color: rgb(153, 188, 244);\n"
"    border-radius: 15px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_12.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.fecha_seleccionada_ventas_totales_diarias = QtWidgets.QDateEdit(self.frame_10)
        self.fecha_seleccionada_ventas_totales_diarias.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 12px;\n"
"color: rgb(52, 64, 85);\n"
"border: none;")
        self.fecha_seleccionada_ventas_totales_diarias.setObjectName("fecha_seleccionada_ventas_totales_diarias")
        self.verticalLayout_12.addWidget(self.fecha_seleccionada_ventas_totales_diarias)
        self.horizontalLayout_19.addWidget(self.frame_10)
        self.boton_generar_ventas_totales_diarias = QtWidgets.QPushButton(self.frame_4)
        self.boton_generar_ventas_totales_diarias.setMinimumSize(QtCore.QSize(30, 30))
        self.boton_generar_ventas_totales_diarias.setMaximumSize(QtCore.QSize(140, 16777215))
        self.boton_generar_ventas_totales_diarias.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 107, 191);\n"
"    color: rgb(255, 255, 255);\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    font-size: 14px;\n"
"    border-radius : 15px;\n"
"}")
        self.boton_generar_ventas_totales_diarias.setObjectName("boton_generar_ventas_totales_diarias")
        self.horizontalLayout_19.addWidget(self.boton_generar_ventas_totales_diarias)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.grafica_ventas_totales_diarias = PlotWidget(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grafica_ventas_totales_diarias.sizePolicy().hasHeightForWidth())
        self.grafica_ventas_totales_diarias.setSizePolicy(sizePolicy)
        self.grafica_ventas_totales_diarias.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.grafica_ventas_totales_diarias.setObjectName("grafica_ventas_totales_diarias")
        self.verticalLayout_6.addWidget(self.grafica_ventas_totales_diarias)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setStyleSheet("QLabel {\n"
"    color: #416BBF;\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    font-size: 18px;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.label_porcentaje_ventas_totales_diarias = QtWidgets.QLabel(self.frame_5)
        self.label_porcentaje_ventas_totales_diarias.setStyleSheet("QLabel {\n"
"    color: #000000;\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"}")
        self.label_porcentaje_ventas_totales_diarias.setObjectName("label_porcentaje_ventas_totales_diarias")
        self.verticalLayout_7.addWidget(self.label_porcentaje_ventas_totales_diarias)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("resources/img/icono_estadistica.png"))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("resources/img/icono_hora_mas_ventas.png"))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setStyleSheet("QLabel {\n"
"    color: #416BBF;\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    font-size: 16px;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.label_hora_mas_ventas_totales_diarias = QtWidgets.QLabel(self.frame_6)
        self.label_hora_mas_ventas_totales_diarias.setStyleSheet("QLabel {\n"
"    color: #416BBF;\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: bold;\n"
"    font-size: 18px;\n"
"}")
        self.label_hora_mas_ventas_totales_diarias.setObjectName("label_hora_mas_ventas_totales_diarias")
        self.verticalLayout_8.addWidget(self.label_hora_mas_ventas_totales_diarias)
        self.horizontalLayout_13.addLayout(self.verticalLayout_8)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("resources/img/icono_hora_menos_ventas.png"))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setStyleSheet("QLabel {\n"
"    color: #416BBF;\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    font-size: 16px;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.label_hora_menos_ventas_totales_diarias = QtWidgets.QLabel(self.frame_7)
        self.label_hora_menos_ventas_totales_diarias.setStyleSheet("QLabel {\n"
"    color: #416BBF;\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: bold;\n"
"    font-size: 18px;\n"
"}")
        self.label_hora_menos_ventas_totales_diarias.setObjectName("label_hora_menos_ventas_totales_diarias")
        self.verticalLayout_9.addWidget(self.label_hora_menos_ventas_totales_diarias)
        self.horizontalLayout_15.addLayout(self.verticalLayout_9)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_15)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.pagina_ventas_totales_diarias)
        self.frame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #99bcf4;\n"
"    border-radius: 15px;\n"
"}")
        self.frame.setObjectName("frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setStyleSheet("QLabel {\n"
"    color: #416BBF;    \n"
"    font-family: \'Montserrat\';\n"
"    fo    nt-style: normal;\n"
"    font-weight: 800;\n"
"    font-size: 20px;\n"
"    text-align: center;\n"
"}")
        self.label_14.setWordWrap(False)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14, 0, QtCore.Qt.AlignHCenter)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setStyleSheet("QLabel {\n"
"    color: #416BBF;    \n"
"    font-family: \'Montserrat\';\n"
"    fo    nt-style: normal;\n"
"    font-weight: 800;\n"
"    font-size: 20px;\n"
"    text-align: center;\n"
"}")
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_10.addWidget(self.label_17, 0, QtCore.Qt.AlignHCenter)
        self.label_dia_ventas_totales_diarias = QtWidgets.QLabel(self.frame)
        self.label_dia_ventas_totales_diarias.setStyleSheet("QLabel {\n"
"    color: #416BBF;    \n"
"    font-family: \'Montserrat\';\n"
"    fo    nt-style: normal;\n"
"    font-weight: 800;\n"
"    font-size: 20px;\n"
"    text-align: center;\n"
"}")
        self.label_dia_ventas_totales_diarias.setWordWrap(True)
        self.label_dia_ventas_totales_diarias.setObjectName("label_dia_ventas_totales_diarias")
        self.verticalLayout_10.addWidget(self.label_dia_ventas_totales_diarias, 0, QtCore.Qt.AlignHCenter)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_16.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.tabla_ventas_totales_diarias = QtWidgets.QTableWidget(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabla_ventas_totales_diarias.sizePolicy().hasHeightForWidth())
        self.tabla_ventas_totales_diarias.setSizePolicy(sizePolicy)
        self.tabla_ventas_totales_diarias.setStyleSheet("QTableWidget::item {\n"
"    border-bottom: 1px solid #C8D0DB;\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 600;\n"
"    color: #000000;\n"
"}\n"
"\n"
"\n"
"")
        self.tabla_ventas_totales_diarias.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tabla_ventas_totales_diarias.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_ventas_totales_diarias.setProperty("showDropIndicator", False)
        self.tabla_ventas_totales_diarias.setDragDropOverwriteMode(False)
        self.tabla_ventas_totales_diarias.setAlternatingRowColors(False)
        self.tabla_ventas_totales_diarias.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tabla_ventas_totales_diarias.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_ventas_totales_diarias.setTextElideMode(QtCore.Qt.ElideRight)
        self.tabla_ventas_totales_diarias.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tabla_ventas_totales_diarias.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tabla_ventas_totales_diarias.setShowGrid(False)
        self.tabla_ventas_totales_diarias.setGridStyle(QtCore.Qt.NoPen)
        self.tabla_ventas_totales_diarias.setWordWrap(False)
        self.tabla_ventas_totales_diarias.setCornerButtonEnabled(False)
        self.tabla_ventas_totales_diarias.setObjectName("tabla_ventas_totales_diarias")
        self.tabla_ventas_totales_diarias.setColumnCount(2)
        self.tabla_ventas_totales_diarias.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_ventas_totales_diarias.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_ventas_totales_diarias.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        item.setFont(font)
        item.setBackground(QtGui.QColor(248, 250, 255))
        brush = QtGui.QBrush(QtGui.QColor(52, 64, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabla_ventas_totales_diarias.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        item.setFont(font)
        item.setBackground(QtGui.QColor(248, 250, 255))
        brush = QtGui.QBrush(QtGui.QColor(52, 64, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabla_ventas_totales_diarias.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tabla_ventas_totales_diarias.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_ventas_totales_diarias.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_ventas_totales_diarias.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_ventas_totales_diarias.setItem(1, 1, item)
        self.tabla_ventas_totales_diarias.horizontalHeader().setVisible(True)
        self.tabla_ventas_totales_diarias.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla_ventas_totales_diarias.horizontalHeader().setHighlightSections(True)
        self.tabla_ventas_totales_diarias.horizontalHeader().setMinimumSectionSize(39)
        self.tabla_ventas_totales_diarias.horizontalHeader().setSortIndicatorShown(False)
        self.tabla_ventas_totales_diarias.horizontalHeader().setStretchLastSection(True)
        self.tabla_ventas_totales_diarias.verticalHeader().setVisible(False)
        self.tabla_ventas_totales_diarias.verticalHeader().setCascadingSectionResizes(False)
        self.tabla_ventas_totales_diarias.verticalHeader().setHighlightSections(False)
        self.tabla_ventas_totales_diarias.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_16.addWidget(self.tabla_ventas_totales_diarias)
        self.verticalLayout_10.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_15 = QtWidgets.QLabel(self.frame_9)
        self.label_15.setStyleSheet("QLabel {\n"
"    color: #344050;\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"}")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_17.addWidget(self.label_15)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem16)
        self.label_total_ventas_totales_diarias = QtWidgets.QLabel(self.frame_9)
        self.label_total_ventas_totales_diarias.setStyleSheet("QLabel {\n"
"    color: #344050;\n"
"    font-family: \'Montserrat\';\n"
"    font-style: normal;\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"}")
        self.label_total_ventas_totales_diarias.setObjectName("label_total_ventas_totales_diarias")
        self.horizontalLayout_17.addWidget(self.label_total_ventas_totales_diarias)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_17)
        self.verticalLayout_10.addWidget(self.frame_9)
        self.horizontalLayout_2.addWidget(self.frame)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_2)
        self.stacked_widget_paginas.addWidget(self.pagina_ventas_totales_diarias)
        self.pagina_ventas_totales_mensuales = QtWidgets.QWidget()
        self.pagina_ventas_totales_mensuales.setObjectName("pagina_ventas_totales_mensuales")
        self.label_4 = QtWidgets.QLabel(self.pagina_ventas_totales_mensuales)
        self.label_4.setGeometry(QtCore.QRect(180, 220, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.stacked_widget_paginas.addWidget(self.pagina_ventas_totales_mensuales)
        self.pagina_ventas_totales_anuales = QtWidgets.QWidget()
        self.pagina_ventas_totales_anuales.setObjectName("pagina_ventas_totales_anuales")
        self.label_6 = QtWidgets.QLabel(self.pagina_ventas_totales_anuales)
        self.label_6.setGeometry(QtCore.QRect(256, 270, 321, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.stacked_widget_paginas.addWidget(self.pagina_ventas_totales_anuales)
        self.pagina_ventas_individuales_diarias = QtWidgets.QWidget()
        self.pagina_ventas_individuales_diarias.setObjectName("pagina_ventas_individuales_diarias")
        self.label_9 = QtWidgets.QLabel(self.pagina_ventas_individuales_diarias)
        self.label_9.setGeometry(QtCore.QRect(220, 280, 351, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.stacked_widget_paginas.addWidget(self.pagina_ventas_individuales_diarias)
        self.pagina_ventas_individuales_mensuales = QtWidgets.QWidget()
        self.pagina_ventas_individuales_mensuales.setObjectName("pagina_ventas_individuales_mensuales")
        self.label_13 = QtWidgets.QLabel(self.pagina_ventas_individuales_mensuales)
        self.label_13.setGeometry(QtCore.QRect(290, 280, 381, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.stacked_widget_paginas.addWidget(self.pagina_ventas_individuales_mensuales)
        self.pagina_ventas_individuales_anuales = QtWidgets.QWidget()
        self.pagina_ventas_individuales_anuales.setObjectName("pagina_ventas_individuales_anuales")
        self.label_16 = QtWidgets.QLabel(self.pagina_ventas_individuales_anuales)
        self.label_16.setGeometry(QtCore.QRect(190, 295, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.stacked_widget_paginas.addWidget(self.pagina_ventas_individuales_anuales)
        self.pagina_empleados = QtWidgets.QWidget()
        self.pagina_empleados.setObjectName("pagina_empleados")
        self.label_3 = QtWidgets.QLabel(self.pagina_empleados)
        self.label_3.setGeometry(QtCore.QRect(130, 230, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setObjectName("label_3")
        self.stacked_widget_paginas.addWidget(self.pagina_empleados)
        self.verticalLayout.addWidget(self.stacked_widget_paginas)
        self.horizontalLayout.addWidget(self.frame_informacion)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stacked_widget_paginas.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boton_ventas_totales.setText(_translate("MainWindow", "Ventas totales"))
        self.boton_ventas_totales_diarias.setText(_translate("MainWindow", "Ventas diarias"))
        self.boton_ventas_totales_mensuales.setText(_translate("MainWindow", "Ventas mensuales"))
        self.boton_ventas_totales_anuales.setText(_translate("MainWindow", "Ventas anuales"))
        self.boton_ventas_individuales.setText(_translate("MainWindow", "Ventas individuales"))
        self.boton_ventas_individuales_diarias.setText(_translate("MainWindow", "Ventas diarias"))
        self.boton_ventas_individuales_mensuales.setText(_translate("MainWindow", "Ventas mensuales"))
        self.boton_ventas_individuales_anuales.setText(_translate("MainWindow", "Ventas anuales"))
        self.boton_empleados.setText(_translate("MainWindow", "Empleados"))
        self.boton_cerrar.setText(_translate("MainWindow", "Cerrar"))
        self.label.setText(_translate("MainWindow", "Soy la pagina por defecto"))
        self.label_2.setText(_translate("MainWindow", "prueba"))
        self.label_tipo_usuario_ventas_totales_diarias.setText(_translate("MainWindow", "TIPO DE USUARIO"))
        self.boton_generar_ventas_totales_diarias.setText(_translate("MainWindow", "Generar"))
        self.label_5.setText(_translate("MainWindow", "Porcentaje de ventas:"))
        self.label_porcentaje_ventas_totales_diarias.setText(_translate("MainWindow", "--.--%"))
        self.label_8.setText(_translate("MainWindow", "Hora con más ventas:"))
        self.label_hora_mas_ventas_totales_diarias.setText(_translate("MainWindow", "--:-- pm/am - --:-- pm/am"))
        self.label_12.setText(_translate("MainWindow", "Hora con menos ventas:"))
        self.label_hora_menos_ventas_totales_diarias.setText(_translate("MainWindow", "--:-- pm/am - --:-- pm/am"))
        self.label_14.setText(_translate("MainWindow", "VENTAS TOTALES DE CAFÉ"))
        self.label_17.setText(_translate("MainWindow", "INDIGO POR DÍA"))
        self.label_dia_ventas_totales_diarias.setText(_translate("MainWindow", "--/--/--"))
        self.tabla_ventas_totales_diarias.setSortingEnabled(False)
        item = self.tabla_ventas_totales_diarias.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tabla_ventas_totales_diarias.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tabla_ventas_totales_diarias.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hora"))
        item = self.tabla_ventas_totales_diarias.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ingresos totales"))
        __sortingEnabled = self.tabla_ventas_totales_diarias.isSortingEnabled()
        self.tabla_ventas_totales_diarias.setSortingEnabled(False)
        item = self.tabla_ventas_totales_diarias.item(0, 0)
        item.setText(_translate("MainWindow", "10:00 am - 11:00 am"))
        item = self.tabla_ventas_totales_diarias.item(0, 1)
        item.setText(_translate("MainWindow", "$15000.00"))
        item = self.tabla_ventas_totales_diarias.item(1, 0)
        item.setText(_translate("MainWindow", "11:00 am - 12:00 pm"))
        item = self.tabla_ventas_totales_diarias.item(1, 1)
        item.setText(_translate("MainWindow", "$10000.00"))
        self.tabla_ventas_totales_diarias.setSortingEnabled(__sortingEnabled)
        self.label_15.setText(_translate("MainWindow", "Total:"))
        self.label_total_ventas_totales_diarias.setText(_translate("MainWindow", "$--.--"))
        self.label_4.setText(_translate("MainWindow", "Soy la pagina ventas totales mensuales"))
        self.label_6.setText(_translate("MainWindow", "Soy la pagina ventas totales anuales"))
        self.label_9.setText(_translate("MainWindow", "Soy la pagina ventas individuales diarias"))
        self.label_13.setText(_translate("MainWindow", "Soy la pagina ventas individuales mensuales"))
        self.label_16.setText(_translate("MainWindow", "Soy la pagina ventas individuales anuales"))
        self.label_3.setText(_translate("MainWindow", "Soy la pagina empleados"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
